CC = movcc
INCLUDES = -I. -I..
COMPILE_C = $(CC) -c $(INCLUDES) -o $@ -Wf--q
LINK = $(CC) -o $@

ALL: softfloat32.o softfloat64.o softfloatfull.o timesoftfloat

milieu.h: 386-MOV.h
	touch milieu.h

softfloat32.o: milieu.h softfloat.h softfloat.c softfloat_specialize.c softfloat_inline.c
	gcc -E softfloat.c -DFLOAT64=0 -DTRIM=1 -o softfloat_nofloat_notrim__inline.c
	sed -i 's;^# [0-9]*[^\$\]*;;g' softfloat_nofloat_notrim__inline.c
	$(CC) -o $@ -c softfloat_nofloat_notrim__inline.c

softfloat64.o: milieu.h softfloat.h softfloat.c softfloat_specialize.c softfloat_inline.c
	gcc -E softfloat.c -DFLOAT64=0 -DTRIM=1 -o softfloat_nofloat_trim__inline.c
	sed -i 's;^# [0-9]*[^\$\]*;;g' softfloat_nofloat_trim__inline.c
	$(CC) -o $@ -c softfloat_nofloat_trim__inline.c 
	
softfloatfull.o: milieu.h softfloat.h softfloat.c softfloat_specialize.c softfloat_inline.c
	gcc -E softfloat.c -DFLOAT64=1 -DTRIM=0 -o softfloat_float_notrim__inline.c
	sed -i 's;^# [0-9]*[^\$\]*;;g' softfloat_nofloat_trim__inline.c
	$(CC) -o $@ -c softfloat_float_notrim__inline.c
	
timesoftfloat.o: milieu.h softfloat.h timesoftfloat.c
	gcc -E timesoftfloat.c -o timesoftfloat__inline.c
	sed -i 's;^# [0-9]*[^\$\]*;;g' timesoftfloat__inline.c
	$(CC) -o $@ -c timesoftfloat__inline.c
	
timesoftfloat: softfloatfull.o timesoftfloat.o
	$(LINK) softfloatfull.o timesoftfloat.o

clean:
	rm -f *.o *.a timesoftfloat *__inline.c
